# Generated by Django 6.0.3 on 2026-04-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Кличка питомца')),
                ('pet_type', models.CharField(max_length=50, verbose_name='Вид животного')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата и время приёма')),
                ('symptoms', models.TextField(blank=True, verbose_name='Симптомы')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONFIRMED', 'Подтверждён'), ('COMPLETED', 'Проведён'), ('CANCELLED', 'Отменён'), ('RESCHEDULED', 'Перенесён')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки врача')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
